<a href="https://colab.research.google.com/github/Trickshotblaster/nn-practices/blob/main/TrigramLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random
import math

In [2]:
import requests

url = 'https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt'
url = 'https://raw.githubusercontent.com/karpathy/makemore/master/names.txt'
#url = 'https://raw.githubusercontent.com/Trickshotblaster/nn-practices/main/TrigramLM.ipynb'
response = requests.get(url)

with open('file.txt', 'wb') as f:
  f.write(response.content)

In [3]:
with open('file.txt', 'r') as data:
  dataset = data.readlines()

with open('file.txt', 'r') as data:
  raw_data = data.read()


In [4]:
dataset = raw_data.split("\n")

In [5]:
dataset[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [6]:
for i, data in enumerate(dataset):
  dataset[i] = "." + data + "."

In [7]:
dataset[:10]

['.emma.',
 '.olivia.',
 '.ava.',
 '.isabella.',
 '.sophia.',
 '.charlotte.',
 '.mia.',
 '.amelia.',
 '.harper.',
 '.evelyn.']

In [8]:
raw_data = ''.join(dataset)

In [9]:
raw_data[:10]

'.emma..oli'

In [10]:
train_set = dataset[:math.floor(len(dataset) * 0.8)]
dev_set = dataset[math.floor(len(dataset) * 0.8):math.floor(len(dataset) * 0.9)]
test_set = dataset[math.floor(len(dataset) * 0.9):len(dataset) - 1]

In [11]:
train_set[:10]

['.emma.',
 '.olivia.',
 '.ava.',
 '.isabella.',
 '.sophia.',
 '.charlotte.',
 '.mia.',
 '.amelia.',
 '.harper.',
 '.evelyn.']

In [12]:
dev_set[:10]

['.amrom.',
 '.aniket.',
 '.ansen.',
 '.apolo.',
 '.aqib.',
 '.aquarius.',
 '.araf.',
 '.arafat.',
 '.areeb.',
 '.ariez.']

In [13]:
test_set[:10]

['.arib.',
 '.arinze.',
 '.aristeo.',
 '.arlind.',
 '.armahni.',
 '.arnez.',
 '.arnie.',
 '.arrie.',
 '.arris.',
 '.arrison.']

In [14]:
vocab = set(raw_data)

In [15]:
vocab

{'.',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [16]:
vocab_len = len(vocab)

In [17]:
vocab_len

27

In [18]:
stoi = {char:i for i, char in enumerate(vocab)}

In [19]:
itos = {i:char for i, char in enumerate(vocab)}

In [20]:
import torch

In [21]:
import torch.nn.functional as functional

In [103]:
# make dataset
xs, ys = [], []
for data in train_set:
  for ch1, ch2, ch3 in zip(data, data[1:], data[2:]):
    xs.append([stoi[ch1], stoi[ch2]])
    ys.append(stoi[ch3])

xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
num

314304

In [23]:
ws = torch.randn((vocab_len*2, vocab_len))
ws.requires_grad = True
ws.shape

torch.Size([54, 27])

In [24]:
xenc = functional.one_hot(xs[0], num_classes=vocab_len).float().flatten()
xenc @ ws

tensor([ 1.2573,  2.4701,  0.7787,  0.3896,  1.7581,  2.5642, -0.4620,  3.1598,
         1.0465, -0.6552,  3.0980,  0.5323,  0.6725, -3.1904,  2.6949, -0.1267,
         0.5389, -0.4035,  0.1498,  2.0171, -0.2992, -0.5798, -0.6729, -0.4913,
        -3.0271, -0.5758,  0.2575], grad_fn=<SqueezeBackward4>)

In [25]:
(xenc @ ws).shape

torch.Size([27])

In [26]:
num_epochs = 100
lr = 20

In [27]:
torch.randn((3, 1))

tensor([[-1.2902],
        [-1.8421],
        [-0.1514]])

In [28]:
for epoch in range(num_epochs):

    xenc = functional.one_hot(xs, num_classes=vocab_len).float().flatten(start_dim=1)
    logits = xenc @ ws
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(int(num / 2)), ys].log().mean() + (ws.mean() * 0.01)
    print(loss.item())

    ws.grad = None
    loss.backward()
    ws.data += ws.grad * -lr

4.214475631713867
3.8153128623962402
3.5331294536590576
3.3370957374572754
3.1890294551849365
3.0709972381591797
2.975813627243042
2.898449182510376
2.8348143100738525
2.781801223754883
2.7371206283569336
2.69905686378479
2.6662890911102295
2.637784481048584
2.61273455619812
2.590508222579956
2.570615768432617
2.5526742935180664
2.5363845825195312
2.5215067863464355
2.507849931716919
2.4952573776245117
2.4836013317108154
2.472775936126709
2.462691068649292
2.4532723426818848
2.444455862045288
2.4361860752105713
2.4284160137176514
2.42110276222229
2.4142098426818848
2.4077041149139404
2.4015557765960693
2.3957388401031494
2.3902292251586914
2.3850045204162598
2.380045175552368
2.375332832336426
2.3708512783050537
2.366584539413452
2.362518310546875
2.358640193939209
2.354937791824341
2.351400375366211
2.3480169773101807
2.3447787761688232
2.3416764736175537
2.338702440261841
2.3358492851257324
2.333109140396118
2.3304765224456787
2.327944755554199
2.3255085945129395
2.323162317276001
2.

In [29]:
xs[:10]

tensor([[ 4,  2],
        [ 2, 21],
        [21, 21],
        [21, 11],
        [ 4,  5],
        [ 5, 13],
        [13,  9],
        [ 9,  8],
        [ 8,  9],
        [ 9, 11]])

In [30]:
def forward(xs):
  xenc = functional.one_hot(xs, num_classes=vocab_len).float().flatten(start_dim=1)
  logits = xenc @ ws
  counts = logits.exp()
  probs = counts / counts.sum(1, keepdims=True)
  outchar = itos[torch.multinomial(probs, num_samples=1).item()]
  return outchar

def prompt(ins):
  out = ins
  for char in range(500):
    last_two = ins[-2:]
    xs = torch.tensor([[stoi[last_two[0]], stoi[last_two[1]]]])
    outs = forward(xs)
    out += outs
  return out

prompt("Rom")

'Romiemvaazzmeiaazatanmxhazaaaoieaeeaib.heir.aahaeiaxaniiaiayyaxa.aiieaaiieeai..adecreibib.iiiioaoyi.aaerdaeiaa..claiiaem.aaeaiepb..ieay.aiaiiieeei..oi.ieaaeyiineixaeaex..eebsiyeeaaaiaeiiagpiaoiaiaao..ieeuai.iaaiiae.afdeaai.mieaaaaae.aaindaeiaiaoiao.iqaobyacioearixeioiiesaa.y.aoiaweiaeabytiaaiyi.vaeiavaiebaaipeeiiawg.iiaaiio..iaiialae.eaabixaei..iadeen.iaeooixoayaaeaaoafah.a.oia.eejeeiatai.fihia.an.iaaeaa.xai.aaxeiaiza.in.aaaakiiaiehita.ena..zszii.yaiuebniiioiiaiexiawezibheizeiei.aaeechenaio.iaaeian'

In [31]:
# make test set
txs, tys = [], []
for data in test_set:
  for ch1, ch2, ch3 in zip(data, data[1:], data[2:]):
    txs.append([stoi[ch1], stoi[ch2]])
    tys.append(stoi[ch3])

txs = torch.tensor(txs)
tys = torch.tensor(tys)
tnum = txs.nelement()
tnum

39052

In [32]:
xenc = functional.one_hot(txs, num_classes=vocab_len).float().flatten(start_dim=1)
logits = xenc @ ws
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)
loss = -probs[torch.arange(int(tnum / 2)), tys].log().mean() + (ws.mean() * 0.01)
print(loss.item())

2.490126371383667


In [33]:
# make dev set
dxs, dys = [], []
for data in dev_set:
  for ch1, ch2, ch3 in zip(data, data[1:], data[2:]):
    dxs.append([stoi[ch1], stoi[ch2]])
    dys.append(stoi[ch3])

dxs = torch.tensor(dxs)
dys = torch.tensor(dys)
dnum = dxs.nelement()
dnum

38860

In [34]:
dxs[:10]

tensor([[ 4, 11],
        [11, 21],
        [21, 22],
        [22,  5],
        [ 5, 21],
        [ 4, 11],
        [11, 24],
        [24,  9],
        [ 9, 16],
        [16,  2]])

In [35]:
xenc = functional.one_hot(dxs, num_classes=vocab_len).float().flatten(start_dim=1)
logits = xenc @ ws
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)
loss = -probs[torch.arange(int(dnum / 2)), dys].log().mean() + (ws.mean() * 0.01)
print(loss.item())

2.4916319847106934


Looks like it might be overfitting? The dev set results seem fine, but the test set loss it much higher than it should be.

In [36]:
ws = torch.randn((vocab_len*2, vocab_len))
ws.requires_grad = True
ws.shape

torch.Size([54, 27])

In [37]:
num_epochs = 100
lr = 20
regularization = 0.01

In [38]:
last_loss = 2.1

for epoch in range(num_epochs):
    dxenc = functional.one_hot(dxs, num_classes=vocab_len).float().flatten(start_dim=1)
    dlogits = dxenc @ ws
    dcounts = dlogits.exp()
    dprobs = dcounts / dcounts.sum(1, keepdim=True)
    dloss = -dprobs[torch.arange(int(dnum / 2)), dys].log().mean() + (ws.mean() * regularization)
    dloss.detach()

    xenc = functional.one_hot(xs, num_classes=vocab_len).float().flatten(start_dim=1)
    logits = xenc @ ws
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(int(num / 2)), ys].log().mean() + (ws.mean() * regularization * (abs(last_loss - dloss)))

    print(loss.item())
    ws.grad = None
    loss.backward()
    ws.data += ws.grad * -lr

    last_loss = loss.item()

4.33623743057251
3.915924549102783
3.618713617324829
3.4117538928985596
3.2597081661224365
3.1400511264801025
3.0420992374420166
2.95998477935791
2.890166997909546
2.830350875854492
2.7788877487182617
2.7344770431518555
2.696033000946045
2.662618637084961
2.6334228515625
2.607752561569214
2.585026979446411
2.5647709369659424
2.546600103378296
2.5302038192749023
2.515331745147705
2.5017786026000977
2.489374876022339
2.4779787063598633
2.467470407485962
2.4577484130859375
2.4487242698669434
2.440324068069458
2.432481288909912
2.425140380859375
2.4182519912719727
2.411773681640625
2.4056668281555176
2.399899482727051
2.394442319869995
2.389270067214966
2.38435959815979
2.3796908855438232
2.3752458095550537
2.37100887298584
2.3669652938842773
2.3631019592285156
2.3594071865081787
2.3558707237243652
2.3524820804595947
2.3492331504821777
2.3461151123046875
2.3431203365325928
2.340242624282837
2.337474822998047
2.3348114490509033
2.3322460651397705
2.3297746181488037
2.3273913860321045
2.3250

In [39]:
prompt("bro")

'bromsknbsgbyohsnw.osc.laonsnbtsocsnsrzfmnnnpsninzlmiczruirn.nnnencnlwnnrh..rfsswnn..tnnb.lnbnauessssnmci.nan.etosqm.recskinbnsgneunnsfonnrnltinncc.b..lylnepsshlie..endcnlu.nu.nn.nnlrovnclepnng.ii.m.wlerqns.undatntrrb.uaohdsansynnnnc.gxnnnrosldarlsnsn.inne.u..s.clwnvian.nnslsmnn.ndlnlson..caylmn.izmlylaokg.seonnlb.esrcnvkssmnynncohsinhsplnmc.ry.rnsllnn.mannbpohnocnulspnhmvfusnsn.lnsaxncotlcnnlsnnmlgns.tlicsulsetsnwrusncuemassnnsndnnv..kmsnhionunsnnsoye.zudnbuunlcssnhecntbdxnbzvtuueacansiennnuw.bnn..'

Idk, maybe? I've definitely screwed something up here but I have no idea what

In [40]:
num_epochs = 100
lr = 20
regularization = 0.1

In [41]:
ws = torch.randn((vocab_len*2, vocab_len))
ws.requires_grad = True
ws.shape

torch.Size([54, 27])

In [42]:
for epoch in range(num_epochs):

    xenc = functional.one_hot(xs, num_classes=vocab_len).float().flatten(start_dim=1)
    logits = xenc @ ws
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(int(num / 2)), ys].log().mean() + (ws.mean() * regularization)

    print(loss.item())
    ws.grad = None
    loss.backward()
    ws.data += ws.grad * -lr



4.206568241119385
3.811091899871826
3.5315661430358887
3.333709239959717
3.187189817428589
3.072943687438965
2.9804868698120117
2.904100179672241
2.8402538299560547
2.7864041328430176
2.7405941486358643
2.7012877464294434
2.667273759841919
2.637592077255249
2.6114771366119385
2.588320255279541
2.5676348209381104
2.5490329265594482
2.5322024822235107
2.516893148422241
2.5029008388519287
2.490058660507202
2.478229522705078
2.4672975540161133
2.4571657180786133
2.447751522064209
2.4389827251434326
2.4307971000671387
2.423140048980713
2.415961265563965
2.4092185497283936
2.4028725624084473
2.396888494491577
2.3912353515625
2.3858845233917236
2.3808114528656006
2.375993013381958
2.3714089393615723
2.3670411109924316
2.362873077392578
2.358889579772949
2.3550775051116943
2.3514254093170166
2.3479223251342773
2.344557285308838
2.3413219451904297
2.3382081985473633
2.3352088928222656
2.3323163986206055
2.3295249938964844
2.3268284797668457
2.3242220878601074
2.3217005729675293
2.31925964355468

In [43]:
prompt('em')

'em.ie.iisabxaaaamae..iiaaaayilyayaeeaeaoig.a.omi.e...yeaa.iiy.aack.maglia.aambatagy..aga.la.ia..raoya..ysag.iina..imagmmaai.aycya.ymwua.iu.a.gmiagimiyy.aiaegi.eabtia...eymaaaaaaii.a.iaoitiaraylai.gaoakm..ia.i.wseiaaa.aa.a.kaoaai.iaag.ymi.e..yoaiaaaimatimaeeiaaa.aiaoet.ie.eaigmiamvaheuii.iiye.y.a.piyiiadeo.sige.os.aoaai.sa.a..lbggihaiilarec.ryebielm.gciy..b.miao.eiagaiiemiitmmahi.taa..iaa.thi..s.yiameria.a.aka.aeeim.oykiaos.aiaa...ragt.aeeiynaisiabameykaaai.i.as.agi.h.yia.aue.g.ooaaaaiaeraaaieaia.a'

Okay this seems promising...

aeoioa, vim, esiaota, aipe, seto, and ioa are all decent

In [44]:
prompt('em')

'emeyyina.l.ej..eagauck.akam.aylieg.eeiisageaceo..basxoiasyb.iaai.it.aioopaaaiiem.a.mi.eilicia.xe..keauyaiiaaaoihaianlikyeetgaixa.aaycioy.iwaba.deitabariyammeiiriaeiia.ra.yp..aket.acimybai.aa.i.a.ti.m..haiea..iaioa.isi.ei.ooilgl.a.haaaxii.oiiy.saace.mx.iail.xiha.aeiayaamiaibg.ia.ibr.s.caat.yaoaaha.aiaaowyxaoae.ei.e..a.gt..ioakil.iyaiaaalas.i.ayugosaeaeaaruaiaimalaaahea..baeamw..oaaaabaayiaoiiok..y.aaiatiemaiaeril.oaa.eii.yteoi.e.a..y.aaoltsiimraagi.aaegaiaaamiillaiei..riio..tiaaaaiibbi.aew.s.iiamim'

In [45]:
ws = torch.randn((vocab_len*2, vocab_len))
ws.requires_grad = True
ws.shape

torch.Size([54, 27])

In [46]:
prompt('em')

'emohgqlqhqqatdxhqq.h.jijoltkmhxqkrlkdwoogkmmldzohfmodzhrq.xdllaqkjmlxwqqijxlzipqhklllimtixjlatoogmmqjrtqrtxqtqgziztwvorhkhqqwqqm.t.tjgxxlmqh.jmxodtxh.qllgkplfzhczazzdwqz.gxqgghqdmqtpltklqzqlqdkhdxwjzrhkittqujgxzllqxqzqjomrlqxzxlxhvrhdqtauqzpgdolhrdqkzqxtqjw.l.xhz.ohgqhlqlzjgxjkzzxirauzmfchpwkhhqqll.qoltzigpxlqlomlhgwlgq.rvqglgxoxkqxozxrhqlpmjqqkkxtkfxkpokkqzqx.qglxqztxetllhp.h.amqhqqetijtvpzwhdp.hophlqkrkdxgmx.twxdoywropq.ztrxplhvoqqqkmxqijimqhkjzlowkxllritqilqjiwbzqkqmdprtihlm.llxdjldvhirtqql.rml'

There's definitely some improvement over base randomness sometimes, but for others, it sucks

In [47]:
regularization = 0.05

In [48]:


for epoch in range(num_epochs):
    dxenc = functional.one_hot(dxs, num_classes=vocab_len).float().flatten(start_dim=1)
    dlogits = dxenc @ ws
    dcounts = dlogits.exp()
    dprobs = dcounts / dcounts.sum(1, keepdim=True)
    dloss = -dprobs[torch.arange(int(dnum / 2)), dys].log().mean() + (ws.mean() * regularization)
    dloss.detach()

    xenc = functional.one_hot(xs, num_classes=vocab_len).float().flatten(start_dim=1)
    logits = xenc @ ws
    counts = logits.exp()
    probs = counts / counts.sum(1, keepdim=True)
    loss = -probs[torch.arange(int(num / 2)), ys].log().mean() + (ws.mean() * regularization)

    print(loss.item(), dloss.item())
    ws.grad = None
    loss.backward()
    ws.data += ws.grad * -lr


3.971431255340576 3.943016290664673
3.604618787765503 3.6434669494628906
3.3425116539001465 3.437258005142212
3.1670732498168945 3.302595376968384
3.0476574897766113 3.20990252494812
2.958189010620117 3.138415813446045
2.8868448734283447 3.080274820327759
2.8282675743103027 3.0319364070892334
2.779283285140991 2.991048574447632
2.737740993499756 2.9559288024902344
2.7020788192749023 2.9253509044647217
2.6711106300354004 2.8983981609344482
2.6439192295074463 2.8743746280670166
2.619793176651001 2.852750062942505
2.5981879234313965 2.833120107650757
2.578686475753784 2.815178632736206
2.5609686374664307 2.798689126968384
2.5447845458984375 2.783466339111328
2.5299363136291504 2.7693612575531006
2.516263008117676 2.756251335144043
2.5036306381225586 2.744034767150879
2.491926431655884 2.7326226234436035
2.4810543060302734 2.7219388484954834
2.4709293842315674 2.711915969848633
2.461479425430298 2.7024948596954346
2.4526400566101074 2.693622589111328
2.44435453414917 2.6852521896362305
2.4

In [49]:
dxs[:10]

tensor([[ 4, 11],
        [11, 21],
        [21, 22],
        [22,  5],
        [ 5, 21],
        [ 4, 11],
        [11, 24],
        [24,  9],
        [ 9, 16],
        [16,  2]])

In [50]:
xs[:10]

tensor([[ 4,  2],
        [ 2, 21],
        [21, 21],
        [21, 11],
        [ 4,  5],
        [ 5, 13],
        [13,  9],
        [ 9,  8],
        [ 8,  9],
        [ 9, 11]])

In [51]:
prompt("em")

'emieiiae.ht.mii.iaia.aigt..i.i.a..eoe.sg.i.iai..aio...aaoab.a.eaal.aeniiaa..ia...eaaal.iimamsm..qq.z..i.imi.eaa.iai.aaalia.aa.aiio.aqioymmiiekizam.aaa.ii..iirari..miaaiahheiyiamehm.i.aoaaa.iqai.ljkzeol.ia.mqi..liaa..aidaiommira.axaeaz.a..iooidaaay.aan..ieiioict.iieaaaaoireiyihioaia....aag.zyahtaieioxeaii.iiiioaegi.alh.ii.zaoeaeaaaaozmagea.yri.mgee.eaiiazeam..bl..iitriaaiaaaimbaaye.iauiidai.ai.tiaaoa.a.hike.ieyjt.aaka.ibaaa.azisia.iiamhimqimaqaamkeasaxiaaia.lue.giiaoaisoga.ai.gi.l.kaaqa.oaiiaqemixi'

High regularization results in a fairly large disparity between normal and dev sets, but it seems to produce better results in odd cases

In [52]:
xenc = functional.one_hot(txs, num_classes=vocab_len).float().flatten(start_dim=1)
logits = xenc @ ws
counts = logits.exp()
probs = counts / counts.sum(1, keepdim=True)

loss = -probs[torch.arange(int(tnum/2)), tys].log().mean()
loss

tensor(2.4858, grad_fn=<NegBackward0>)

In [53]:
ws.shape

torch.Size([54, 27])

Wait

In [54]:
ws = torch.randn((vocab_len, vocab_len, vocab_len))
ws.requires_grad = True
ws.shape

torch.Size([27, 27, 27])

In [55]:
xenc = functional.one_hot(xs, num_classes=vocab_len).float()
xenc.shape

torch.Size([157152, 2, 27])

In [56]:
xenc[0].shape

torch.Size([2, 27])

In [57]:
(xenc[0] @ ws).shape

torch.Size([27, 2, 27])

Holup, gotta learn matrix multiplication again, it's hard being a 3 dimensional being trying to comprehend 700 dimensional math

In [61]:
2 + 9 + 25

36

In [62]:
a = torch.tensor([[2, 8, 3],
                 [5, 4, 1]])

b = torch.tensor([[4, 1],
                 [6, 3],
                 [2, 4]])
# each row/column is an n tuple
# dot product of (a, b), (c, d) is a*b + c*d

a @ b


tensor([[62, 38],
        [46, 21]])

In [78]:
inputs = torch.randn((2)) # inputs transposed?
print(inputs)


w1 = torch.randn((2, 1))  # (num in prev, num in target)
print(w1)
inputs @ w1

tensor([-0.7574,  1.0536])
tensor([[-2.0325],
        [ 1.6530]])


tensor([3.2809])

In [79]:
inputs = torch.randn(10) # 10 inputs (same as randn(1, 10))

w1 = torch.randn(10, 3) # takes in 10, goes to 3 neurons
w2 = torch.randn(3, 8) # holy moly this is so easy bruh i was overcomplicating it
w3 = torch.randn(8, 1) # take in 8, to 1 neuron

wi1 = inputs @ w1
wi2 = wi1 @ w2
wi3 = wi2 @ w3
wi3

tensor([-3.4648])

In [81]:
xenc[0].shape

torch.Size([2, 27])

In [82]:
xenc[0] @ torch.randn(27, vocab_len)

tensor([[-0.7646, -0.0553, -0.4053,  1.8639,  1.4675,  0.7353, -0.4238, -1.2535,
          2.0136, -1.3031, -0.2571, -1.6782,  0.6640, -0.8705,  0.0198,  1.6297,
          0.5460,  0.1690, -1.5488, -0.2828,  0.9880, -0.7373,  0.1677,  0.1624,
          0.9211, -0.3307,  0.6290],
        [ 0.8657,  0.0252,  0.5934, -0.4846,  0.8430,  0.0939,  1.6689, -1.2057,
         -0.1189,  2.4480, -0.4950, -0.0997,  0.3654, -0.1148, -0.4170,  0.5566,
          0.1468,  0.2316, -0.8801, -1.1140,  1.5191,  1.4787, -0.4355, -0.7154,
         -0.6429, -0.8687,  0.0854]])

ok maybe I wasn't as wrong as I thought. Other people might just be counting each individual trigram and doing a one_hot with num_classes as 27*27, while I just had a 'two-hot' tensor with the shape of (1, 54).

In [104]:
# make dataset
xs, ys = [], []
for data in train_set:
  for ch1, ch2, ch3 in zip(data, data[1:], data[2:]):
    xs.append([stoi[ch1], stoi[ch2]])
    ys.append(stoi[ch3])

xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
num

314304

In [106]:
xs[:10]

tensor([[ 4,  2],
        [ 2, 21],
        [21, 21],
        [21, 11],
        [ 4,  5],
        [ 5, 13],
        [13,  9],
        [ 9,  8],
        [ 8,  9],
        [ 9, 11]])

In [117]:
# xenc how?
# 729 classes bc 27*27
ab = functional.one_hot(torch.tensor([stoi['a'], functional.one_hot(stoi['b'], num_classes=27)]), num_classes=27)
ba = functional.one_hot(torch.tensor([stoi['b'], stoi['a']]), num_classes=27)
zz = functional.one_hot(torch.tensor([stoi['z'], stoi['z']]), num_classes=27)
print(torch.argmax(ab), torch.argmax(ba), torch.argmax(zz)) # guess it works?

tensor(11) tensor(14) tensor(1)


In [120]:
xenc = functional.one_hot(torch.tensor([functional.one_hot(x, num_classes=vocab_len) for x in xs]), num_classes=vocab_len).float()
xenc.shape

TypeError: ignored

In [115]:
torch.argmax(xenc[0])

tensor(4)

In [114]:
ws = torch.randn(vocab_len**2, vocab_len)
(xenc @ ws).shape

torch.Size([157152, 2, 27])